In [4]:
import torch
import numpy as np


In [5]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float64)
print(f"Rand tensor: \n {x_rand} \n")


Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Rand tensor: 
 tensor([[0.5752, 0.0870],
        [0.0259, 0.3788]], dtype=torch.float64) 



In [8]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor} \n")


Random tensor: 
 tensor([[0.9812, 0.6522, 0.6666],
        [0.2009, 0.4279, 0.9794]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [9]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape} \n")
print(f"Datatype of tensor: {tensor.dtype} \n")
print(f'Device tensor is stored on: {tensor.device} \n')



Shape of tensor: torch.Size([3, 4]) 

Datatype of tensor: torch.float32 

Device tensor is stored on: cpu 



In [10]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")
print(f'Device tensor is stored on: {tensor.device} \n')

Device tensor is stored on: cpu 



In [11]:
tensor = torch.ones(4, 4,)
print(f"First Row: {tensor[0]}")
print(f"First Column: {tensor[:, 0]}")
print(f"Last Column: {tensor[:, -1]}")
tensor[:, 1] = 0
print(tensor)

First Row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
Last Column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [15]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [16]:
t1 = tensor * tensor
t2 = tensor.mul(tensor)

t3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=t3)

print(t1)
print(t2)
print(t3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
agg = tensor.sum()
agg = agg.item()
print(agg, type(agg))

12.0 <class 'float'>


In [18]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [19]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [20]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
n = np.ones(6)
t = torch.from_numpy(n)
print(n)
print(t)


[1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
np.add(n, 1, out=n)
print(n)
print(t)

[2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)
